"""update tables nuulable

Revision ID: e9b256ca8d3a
Revises: 7899284025fe
Create Date: 2024-07-29 14:51:06.502524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b256ca8d3a'
down_revision: Union[str, None] = '7899284025fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('forms', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('responses', 'selected_option',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('responses', 'selected_option',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('forms', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
